### ISSUE TITLE
Support for using higher ports for built-in webserver

### ISSUE THREAD

**Issue by peteraba** [aphiria/aphiria#114]
### Problem
On OSX using port 80 is not available for users by default:

```
> php aphiria app:serve
Running at http://localhost:80
[Mon Feb  1 08:55:10 2021] Failed to listen on localhost:80 (reason: Permission denied)
```

Of course there are workarounds, but it's probably best to just avoid using port 80 as default, at least this is what most tools would do.

Now it seems like providing a port is supported:
```
> php aphiria app:serve --port 10080
Running at http://localhost:10080
[Mon Feb  1 08:57:01 2021] PHP 8.0.1 Development Server (http://localhost:10080) started
```

Unfortunately however, this will cause some issues when the endpoint is hit:
```
> curl http://localhost:10080/
{"type":"https:\/\/tools.ietf.org\/html\/rfc7231#section-6.5.4","title":"No route found for http:\/\/localhost:10080\/","detail":null,"status":404,"instance":null}
```

### Expectation

At least one, but perhaps all of the following:
1. Use a higher port by default.
2. When a higher port is used, the localhost router should still work properly.
3. Documentation should make it obvious what to change when a different port is being used.

**Comment by davidbyoung** [comment]
Thanks for reporting!

1. Sounds good, I'll update the default port number
2. The localhost router _should_ still work with another port.  Are you sure you're actually hitting a route?  There is no root route registered in the demo app.
3. If I am correct with 2, I think the docs won't need updating

**Comment by davidbyoung** [comment]
I've updated the [app](https://github.com/aphiria/app/pull/15) and [docs](https://github.com/aphiria/docs/pull/7), too

**Comment by peteraba** [comment]
great job @davidbyoung !

> There is no root route registered in the demo app.
I think this caught me off guard then. 😉
