### ISSUE TITLE
Can not readLine from console input

### ISSUE THREAD

**Issue by leprz** [aphiria/aphiria#121]
Hi, I got this issue on Windows
![image](https://user-images.githubusercontent.com/5104754/110273993-1c511b00-7fce-11eb-9e90-2099210d5893.png)

I can not read any input from the console.
I tried to use different consoles (git bash, cmd, power shell)

It fails on the `\Aphiria\Console\Output\StreamOutput::readLine`

`feof` return false here.  The `$input` is present and have correct value inserted in the console
```php
public function readLine(): string
{
    $input = \fgets($this->inputStream, 4096);

    if (!\feof($this->inputStream)) {
        throw new RuntimeException('Failed to read line');
    }

    return $input;
}
```

I've checked similar functionality on symfony console `\Symfony\Component\Console\Helper\QuestionHelper::readInput`
They just return fgets result. Is there a reason to check for EOL while reading one line?
```php
if (!$question->isMultiline()) {
    return fgets($inputStream, 4096);
}
```

**Comment by davidbyoung** [comment]
Thanks for reporting!  Should be fixed.

**Comment by leprz** [comment]
It works now! Thanks  🥇
